#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Chenla Primer
#+STARTUP: showall
#+PROPERTY: filename 
#+INCLUDE: ./inc/head.org
#+HTML_HEAD: <link href="./css/index.css" rel="stylesheet" type="text/css" />
  :PROPERTIES:
  :Name: /home/deerpig/proj/deerpig/deerpig-install/index.org
  :Created: 2016-08-20T16:40@Wat Phnom (11.5733N17-104.925295W)
  :ID: 5995dc73-91da-4940-bae1-efb75ce040d4
  :URL:
  :END:
#+INCLUDE: ./inc/macros.org
#+INCLUDE: ./inc/links.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* About these pages

#+begin_quote
The Primer is an encyclopedia of sorts, with descriptive and
proscriptive articles that document the knowledge, designs and code
needed to build and maintain a technologically advanced distributed
civilization for mankind.
#+end_quote

* Recent Activity

Recent change activity on http://github.com/deerpig/deerpig-install

#+BEGIN_SRC sh :exports results :results silent
githubchart -u deerpig ./img/contrib.svg
#+END_SRC

#+RESULTS:

[[./img/contrib.svg]]

#+HTML: <div class="contrib-legend text-small text-muted" title="A summary of pull requests, issues opened, and commits to the default and gh-pages branches.">
#+HTML:  <span>Less</span>
#+HTML:   <ul class="legend">
#+HTML:     <li style="background-color: #eee"></li>
#+HTML:     <li style="background-color: #d6e685"></li>
#+HTML:     <li style="background-color: #8cc665"></li>
#+HTML:     <li style="background-color: #44a340"></li>
#+HTML:     <li style="background-color: #1e6823"></li>
#+HTML:   </ul>
#+HTML:  <span>More</span>
#+HTML: </div>

* Introduction

The organization of encyclopedias is flat -- an encypledia is
typically just a bunch of articles (JBOA) that are arranged
alphabetically when physical printed and bound.

The Primer can also be seen as a JBOA, but also includes links between
articles and between different block and inline content within
articles.  In this respect it can be seen as a wiki like Wikipedia.

However links in the Primer are layered into a stack:

  - Thread Layer
  - Reference Layer
    - other articles
    - external contents
    - blobs
    - authorities
    - controlled vocabularies
  - Relationship Layer
  - Annotative Layer
    - glossa
    - scholia
  - Version Layer

** Composed vs. Generative Links
** Rulesets
** Duck Tests

* Organization

 - topicspaces
 - blob tree

* Maps vs Source

This repo is the source code for the Primer -- when it is
compiled, all of the rule sets and ducktests will be applied
and cascade and generate an index which can be imported into
a graph database, and formated articles in a variety of
formats from plain text, html, LaTex (pdf) etc.

* Navigating a Labryinth

  - ariandies string
  - breadcrumbs

The primer can be thought of as a /threaded rhizomatic
labyrinth/.  For modern  

#+begin_quote
But he soon found to his dismay that the treatment of the
chronicle material was singularly unlike wht he had see in
the /Morte Arthure/.  Adventures were piled up one upon the
other other without any apparent sequence or design, and
innumerable personages, mostly anonymous, were introduced in
a wild succession.  Every now and thenthey stopped to lay
lance in rest and overthrow each other, and then swore
eternal friendship and rode away.  The pupose of their
encounters and pursuits was vague, and their tasks were
seldom fulfilled: they met and parted and met again, each
intent at first on following his particular 'quest', and yet
prepared at any time to be diverted from it to other
adventures and undertakings.  As a result, 'the basic
thought became subsidiary, the episode increasingly
prominent, the showing of the action defeated any attempt to
reach an end and the story lost all purpose.' In these words
Gustav Gröber described three-quarters of a century ago the
methods used by medieval prose writers.  But there is reason
to believe that at a much earlier date their methods were
condemned on similar grounds, and the often quoted remark of
the Canon of Toledo in /Don Quixote/ remains to this day the
most characteristic epression of the modern view: 'I have
never yet,' he says, 'seen in a book of chivalry complete in
all its parts, so that the middle agrees with the beginning
and the end with the beginning and the middle; but they seem
to construct heir stories with such a multitude of members
as though they meant to produce a monster rather than a
well-proportioned figure.'

The real question is, however, whether neglect of
/structure/ in the modern sense of the term neccessarily
implies that absence of a /method of composition/. Gröber may
have blamed the cycle works for their lack of a
/Grundgedanke/, Cervantes may have thought them 'monsterous'
because they formed no consistent whole; but it remains to
be seen whether the criteria of a /Grundgedanke/ or of a
'well-proportioned figure' are not in this case misleading,
and weather behind the apparent deformity and incoherence of
the prose romances there is not to be found an architectual
design so unlike our own conception of a story that we
inevitably fail to percieve it.  One /a priori/ reason for
suspecting the existence of such a design is that if each
branch of the Cycle were a mere collection of episodes
haphazzardly put together, the Cycle would naturally fall
into as many independent sections.  In reality, the reverse
is the case; none of the branches of the Cycle can be
conveniently subdivided, and no subdivisions exist in the
manuscripts.  Apart from certain interpolations which can
easily be detached from the main body of the work, few of
the episodes if any, appear as self-contained units. 'Aucune
aventure', writes Ferdinand Lot, 'ne forme un tout se
suffisant à lui-même.  D'une part, des èpisodes antérieurs,
laissés provisoirement de côté, y prolongent des
ramifications' d'autre part, des épisodes sebséquents,
proches ou lointains, y sont ameorcés'[1]  Judged by our
standards this would seem to be a strange paradox.  On the
one hand, the prose romances are admittedly, the very
negation of the classical principle of composition: the
beginning does not 'agree' with the middle, nor the middle
with the end; on the other, they seem to obey the age-long
rule that no part can be removed without effecting the
whole.  There must, then be something which binds them
together, invisible though it is to the modern eye: some
peculiar device which, while making the various parts of the
Cycle inseparable from one another, fails to weld them into
an harmonious whole.

Perhaps the easiest way to discover the nature and the
working of this device is to draw an analogy with the
technique of tapestry.  Just as in a tapestry each thread
alternates with an endless variety of others, so in the
early prose romances of the Arthurian group numerous
seemingly indepdendent episodes or 'motifs' are interwoven
in a matter which makes it impossible for each episode to be
set aside at any moment and resumed later.  No single
stretch of such a narrative can be complete in itself any
more than a stitch of such a narrative can be complete in
itself a woven fabric; the sequel may appear at any moment,
however long the interval.  But the resemblance goes
further, for unlike the finished tapestry, a branch of prose
romance has as a rule no natural conclusion; when the author
brings it to a close he simply cuts the threads at
arbitrarily chosen points, and anyone who chooses to pick
them up and interweave them in a simular fashion cancontine
the work indefinitely. Hence the 'multitude of members' and
the prodigious growth of the Arthurian tradition enlarged at
each stage of its progress by continuations of earlier works.

-- Eugène Vinaver Vinaver | The Works of Sir Thomas 
   Malory v1.pg lxiv-lxvii.

/The Works of Sir Thomas Malory/. Ed. Vinaver, Eugène
(1967). 2nd ed. 3 vol. Oxford: Clarendon Press. [[https://en.wikipedia.org/wiki/Special:BookSources/0198118384][ISBN 0-19-811838-4]].

:SEE: [[https://en.wikipedia.org/wiki/Le_Morte_d%27Arthur][Le Morte d'Arthur]] | Wikipediaq

[[https://en.wikipedia.org/wiki/Gustav_Gr%C3%B6ber][Gustav Gröber]]  | Wikipedia
[[https://en.wikipedia.org/wiki/Eug%C3%A8ne_Vinaver][Eugène Vinaver]] | Wikipedia


[1] Does not form a whole sufficient to itself. On the one
hand, earlier episodes, temporarily left aside, prolong
desramifications, and on the other hand, sequent episodes,
close or distant, are brought to light
#+end_quote



that is a /paedia/ of
  descriptive and prescriptive topics which are made up of a
  narratives, rulesets and media

, authorities and library

