#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Chenla Primer | TOC
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-TOC-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

bibliography:../hoard/bib.bib

* About
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/primer/index.org
:Created:   2016-08-20T16:40@Wat Phnom (11.5733N17-104.925295W)
:ID:        5995dc73-91da-4940-bae1-efb75ce040d4
:VER:       557691003.681674029
:GEO:       48P-491193-1287029-15
:BXID:      proj:XCA6-8881
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:


** Primer Core

Since each stage is culmulative, and most things in the
primer are, well, primitives -- there are structures at all
stages -- but there will be different knowledge and keystone
designs for each stage, each building on the other beneath
it.

** Survival

In a larger sense the primer should be structured like a
reverse onion, that starts off with nothing except pictures
which determine where you are and what your situation is.

Each layer will branch -- if you can demonstrate that you
have the cognitive skills and knowledge to unlock the next
layer -- it will unlock.

A pre-industrial level of technology should not unlock
knowledge that can destroy it unless it demonstrates it can
handle it responsibly.  This will also ensure that people
master layers that they need to understand before they can
understand the deeper layers.  The cool thing is that
because we are writing this after mankind has gone through
the messy process of learning and mastering it all the first
place we can build something that will not only be faster,
but will provide benifits early on that we didn't have the
first time around.  The idea of germs, bacteria, viruses
etc. and sanitation.  We can introduce anesthesia and
techniques for choking or restarting a heart and
respiration very early.

Are you on a planet with pressurized atmosphere oxygen?

If yes:

   Do you have water, food, fire, shelter.  Is something
   hunting you?

   Then clothes, preserving food, and a bunch of things that
   will create enough surplus time and safety to be able to
   master languages etc.

   Then basics of language, then written language

   From there layers will progressively build up a
   technological civilization from a neo-18th century
   beginning with tools and basic mechanical machines --
   then the jump to electricity, electronics and eventually
   space travel.

If no:

   Then you are likely in a disfunctional technological
   civilization and there are easier ways of rebuilding a
   civilization through reclamation and recycling materials
   and other resources.

** Building a Civilization

The idea here is that the primer will use patterns from APPL
to put together larger generative structures that a
civilization is built on.  The primer deals in principles,
standards, best practices etc.

You can't really use patterns directly -- that might be one
reason that APL hasn't been as useful for the design and
construction of buildings because it assumed all this other
knowledge that wasn't made explicit.  There are ways of
applying patterns in a cold climate, another for applying
the same patterns in the tropics and another in artificial
habitats in space or hostile environments like Mars.

Next, Patterns, in themselves, are not generative -- that's
what I hope the Primer can provide -- generative structures
for building a civilization.  That is a /very/ hard problem.




** Origins
This is the primer for building origin stories, not an
actual origin story -- those will go into a Hoard.
**** References

 - [[https://www.quantamagazine.org/scientist-questions-the-link-between-oxygen-and-cambrian-animal-evolution-20180321/][Complex Animals Led to More Oxygen, Says Maverick
   Theory]] | Quanta

 - Butterfield, N. J. (2017). Oxygen, animals and aquatic
   bioturbation: an updated account. Geobiology, 16(1),
   3–16. http://dx.doi.org/10.1111/gbi.122
** Education
This is the primer for building an educational system, not
actual study programs -- those will go into a Hoard.
** Science
** Tools
** Machines
 - hand machines
 - transporation
 - 
** Structures
** Energy
** Systems
** Agriculture
** Culture
** Commerce
** x. Meta

These documents define how the Primer is structured and the
rules and guidelines to build it.  They don't consitute the
primer itself, which will be a collection of topicspaces,
articles and threads.

To use Wikipedia's nomenclature, these are the the Primer's
/meta/ pages.  We're calling it Primer for now until we have
a clear idea how base articles and threads will be
structured and formated.  At that time these docs will be
moved into a /primer-meta/ repository of their own.

Even more meta than the /Primer Meta/ will be the BMF
specfications that the Primer will be built on.

Turtles all the way down indeed....

**** Table of Contents

 - [[./prim-introduction.org][Introduction]]

 - Manifesto
 - Theses
 - Roadmap For Mankind

 - [[./prim-naming-conventions.org][Naming Conventions]]
 - [[./prim-strategies.org][Strategies for a Distributed Civilization]]
 - [[./primer-persons.org][Persons]]

 WAPT

 - works
 - authorities
 - patterns
 - terms
