#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Chenla Primer
#+STARTUP: showall
#+PROPERTY: filename 
#+INCLUDE: ./inc/head.org
#+HTML_HEAD: <link href="./css/index.css" rel="stylesheet" type="text/css" />
  :PROPERTIES:
  :Name: /home/deerpig/proj/deerpig/deerpig-install/index.org
  :Created: 2016-08-20T16:40@Wat Phnom (11.5733N17-104.925295W)
  :ID: 5995dc73-91da-4940-bae1-efb75ce040d4
  :URL:
  :END:
#+INCLUDE: ./inc/macros.org
#+INCLUDE: ./inc/links.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* About these pages

#+begin_quote
The Primer is an encyclopedia of sorts, with descriptive and
proscriptive articles that document the knowledge, designs and code
needed to build and maintain a technologically advanced distributed
civilization for mankind.
#+end_quote

* Recent Activity

Recent change activity on http://github.com/deerpig/deerpig-install

#+BEGIN_SRC sh :exports results :results silent
githubchart -u deerpig ./img/contrib.svg
#+END_SRC

#+RESULTS:

[[./img/contrib.svg]]

#+HTML: <div class="contrib-legend text-small text-muted" title="A summary of pull requests, issues opened, and commits to the default and gh-pages branches.">
#+HTML:  <span>Less</span>
#+HTML:   <ul class="legend">
#+HTML:     <li style="background-color: #eee"></li>
#+HTML:     <li style="background-color: #d6e685"></li>
#+HTML:     <li style="background-color: #8cc665"></li>
#+HTML:     <li style="background-color: #44a340"></li>
#+HTML:     <li style="background-color: #1e6823"></li>
#+HTML:   </ul>
#+HTML:  <span>More</span>
#+HTML: </div>

* Introduction

The organization of encyclopedias is flat -- an encypledia is
typically just a bunch of articles (JBOA) that are arranged
alphabetically when physical printed and bound.

The Primer can also be seen as a JBOA, but also includes links between
articles and between different block and inline content within
articles.  In this respect it can be seen as a wiki like Wikipedia.

However links in the Primer are layered into a stack:

  - Thread Layer
  - Reference Layer
    - other articles
    - external contents
    - blobs
    - authorities
    - controlled vocabularies
  - Relationship Layer
  - Annotative Layer
    - glossa
    - scholia
  - Version Layer

** Composed vs. Generative Links
** Rulesets
** Duck Tests

* Organization

 - topicspaces
 - blob tree

* Maps vs Source

This repo is the source code for the Primer -- when it is
compiled, all of the rule sets and ducktests will be applied
and cascade and generate an index which can be imported into
a graph database, and formated articles in a variety of
formats from plain text, html, LaTex (pdf) etc.

* What's included in the Primer?

The primer can be thought of as a /rhizomatic/ /labyrinth/ 

#+begin_quote
But he soon found to his dismay that the treatment of the
chronicle material was singularly unlike wht he had see in
the /Morte Arthure/.  Adventures were piled up one upon the
other other without any apparent sequence or design, and
innumerable personages, mostly anonymous, were introduced in
a wild succession.  Every now and thenthey stopped to lay
lance in rest and overthrow each other, and then swore
eternal friendship and rode away.  The pupose of their
encounters and pursuits was vague, and their tasks were
seldom fulfilled: they met and parted and met again, each
intent at first on following his particular 'quest', and yet
prepared at any time to be diverted from it to other
adventures and undertakings.  As a result, 'the basic
thought became subsidiary, the episode increasingly
prominent, the showing of the action defeated any attempt to
reach an end and the story lost all purpose.'"

Eugène Vinaver Vinaver | The Works of Sir Thomas Malory v1.pg lxiv-lxv.

/The Works of Sir Thomas Malory/. Ed. Vinaver, Eugène
(1967). 2nd ed. 3 vol. Oxford: Clarendon Press. [[https://en.wikipedia.org/wiki/Special:BookSources/0198118384][ISBN 0-19-811838-4]].

:SEE: [[https://en.wikipedia.org/wiki/Le_Morte_d%27Arthur][Le Morte d'Arthur]] | Wikipedia

[[https://en.wikipedia.org/wiki/Gustav_Gr%C3%B6ber][Gustav Gröber]]  | Wikipedia
[[https://en.wikipedia.org/wiki/Eug%C3%A8ne_Vinaver][Eugène Vinaver]] | Wikipedia
#+end_quote




that is a /paedia/ of
  descriptive and prescriptive topics which are made up of a
  narratives, rulesets and media

, authorities and library

