#   -*- mode: org; fill-column: 60 -*-
#+TITLE: 
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/primer/prim-name-conventions.org
  :Created: 2017-02-10T21:17@Prek Leap (11.642600N-104.919210W)
  :ID: c8bde840-8129-412b-80a6-3d3cef6ef4d7
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>

* Introduction

#+begin_quote
There are only two hard things in Computer Science: cache invalidation
and naming things.

-- Phil Karlton
   :source: https://martinfowler.com/bliki/TwoHardThings.html
   quote was confimed by Tim Bray
#+end_quote

#+begin_quote
What is above all needed is to let the meaning choose the word, not
the other way around.

... the worst thing one can do with words is surrender to them.


  - i.   Never use a metaphor, simile, or other figure of speech which
         you are used to seeing in print.
  - ii.  Never use a long word where a short one will do.
  - iii. If it is possible to cut a word out, always cut it out.
  - iv.  Never use the passive where you can use the active.
  - v.   Never use a foreign phrase, a scientific word, or a jargon
         word if you can think of an everyday English equivalent.
  - vi.  Break any of these rules sooner than say anything outright
         barbarous.

-- George Orwell | Politics and the English Language
   [[http://wikilivres.ca/wiki/Politics_and_the_English_Language][Politics and the English Language]] | Wikilivres
   [[http://www.orwell.ru/library/essays/politics/english/e_polit/][George Orwell: Politics and the English Language]]
#+end_quote


#+begin_quote
I overheard some people deciding that they need more layers in their
architecture. They were right, as it happens; but going about it a
little backwards. They were attempting to create a framework that
would contain the business logic. Rather than solving some specific
problems they started with the idea that they want a framework that
wraps the database up and produces objects. And it should use
object-relational mapping. And messages. And web services. And it
should do all sorts of cool stuff.

Unfortunately, since they didn't exactly know what cool stuff it would
do, they didn’t know what to call it. So they held a little
competition to suggest a name. And that is the point at which you must
recognise that you have a problem: if you don’t know what a thing
should be called, you cannot know what it is. If you don’t know what
it is, you cannot sit down and write the code.

In this particular case, a quick browse throught the source control
history revealed the depth of the problem. Of course, there were lots
of empty interface "implementations"! And the really funny thing is
that they had already changed the names three times with no actual
code. When they started they called it ClientAPI -- the “client”
refers to the customers of the business, not client as in
“client-server”-- and the final version was called
ClientBusinessObjects. Great name: vague, broad and misleading.

Of course, in the end, a name is just a pointer. Once everyone
involved knows that the name is just a name and not a design metaphor
then you can all move on. However, if you can't agree on a name that
is specific enough for you to know when it is wrong, then you might
have some difficulty even getting started. Design is all about trying
to fulfil intentions -- e.g., fast, cheap, flexible -- and names
convey intentions.

If you can’t name it, you can’t write it. If you change the name 3
times, then you should stop until you know what you are trying to
build.

 By Sam Gardiner 
 This work is licensed under a Creative Commons Attribution 3 


-- Sam Gardiner |
   [[http://97things.oreilly.com/wiki/index.php/A_rose_by_any_other_name_will_end_up_as_a_cabbage][A rose by any other name will end up as a cabbage - Softarch 97Things]]
#+end_quote



Naming conventions are not to be taken lightly

---

- [[http://stackoverflow.com/questions/33497879/why-is-the-hardest-part-of-programming-is-naming-things][Why is the hardest part of programming is naming things?]] | Stack Overflow
- [[http://wiki.c2.com/?MeaningfulName][Meaningful Name]]
- [[http://www.slideshare.net/pirhilton/how-to-name-things-the-hardest-problem-in-programming][How to name things: the hardest problem in programming]] Peter
  Hilton | Slideshare
- [[http://hilton.org.uk/presentations/naming][How to name things]] Peter Hilton]
- [[https://news.ycombinator.com/item?id=9598527][How to name things in programming]] | Hacker News Comment Thread


* Names and Magic

Naming is perhaps /the/ single most /human/ activity we as a species
do.

The names we give things have long been thought to have power over
what is named

It's still not uncomon in Jamacia for people to only give out
nicknames for each other, because knowledge of a persons real name
gives others, who practice the dark arts, to bring them to harm.

   - /look up essay on guy trying to write Bunny Wailer's Bio/

* Mythology

  - Tutonic Mythology
  - Golden Bough
  - Joseph Campbell
  - Tolkien

 - [[bib:cassirer:2012language][Language and Myth]] | Ernst Cassirer


* Wikipedia Naming Conventions

  - [[https://en.wikipedia.org/wiki/Wikipedia:Article_titles][Wikipedia:Article titles]] | Wikipedia
  - [[https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style#Article_titles][Wikipedia:Manual of Style § Article titles]] 
  - [[https://en.wikipedia.org/wiki/Wikipedia:Naming_conventions_(technical_restrictions)][Wikipedia:Naming conventions (technical restrictions)]]
  - [[https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Trademarks][Wikipedia:Manual of Style/Trademarks]] 
  - [[https://en.wikipedia.org/wiki/Wikipedia:Lead_section#Alternative_names][Wikipedia:Lead section § Alternative names]] 
  - [[https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style#National_varieties_of_English][Wikipedia:Manual of Style, National varieties of English]] 
  - [[https://en.wikipedia.org/wiki/Wikipedia:Neutral_point_of_view#Naming][Wikipedia:Neutral point of view § Naming]]
  - [[https://en.wikipedia.org/wiki/Wikipedia:Official_names][Wikipedia:Official names]] | essay

* MARC

  - [[http://www.loc.gov/marc/naming.html][Naming Conventions for Digital Resources]] 
  - [[https://www.loc.gov/marc/bibliographic/bdx00.html][Format for Bibliographic Data |]] MARC
  - [[https://www.loc.gov/marc/authority/adx00.html][Format for Authority Data]] | MARC
  - [[https://www.loc.gov/marc/bibliographic/bd100.html][Main Entry-Personal Name]] | MARC

* Scientific Naming

  - [[http://www.nationalgeographic.org/activity/how-scientists-name-things/][How Scientists Name Things]] | National Geographic Society
