#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Strategies for a Distributed Civilization
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/primer/prim-strategies.org
  :Created: 2017-02-17T15:26@Prek Leap (11.642600N-104.919210W)
  :ID: 88ce5b99-373d-4f6e-a4c7-2cd6e9ec0dc7
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>

* Introduction

Mollison's final section of PDM (Permaculture A Designer's Manual) was
devoted to /Strategies for An Alternate Nation/ in which he outlined
in some detail how to built communities and whole economies based on
the Permaculture concepts laid out in the book.  There are some very
good ideas, mostly based in practical experience of things that have
worked before.

We will use this part of the Primer to do the same, but it will
include actual designs, code, and models that can be used for planning
and eventually as a foundation for building and governing Scopic
Distributed Communities.

When I first approached the problem of how to build a new civilization
I basically passed on the idea.  It was too big, and it was utter
hubris to think that a civilization could be designed top down.  So I
concentrated on the idea of building a distributed group of small
communities that were designed collectively to become caretakers of
mankind's collective memory and experience.  When things got bad,
these communities could then come in and restore knowledge whenever
and wherever it was lost.  The model that was at the back of my mind
was the medieval monastary.  These were and still are today stable
communities that have survived centuries and have indeed been the last
refuge of much of mankind's recorded knowledge that was preserved
through centuries of darkness.  There is a reason these centuries were
called the Dark Ages.  And every civilization has gone through
numerous dark Ages.  Greek Civilization emerged from such a Dark Age
and the Illiad and Odyssey are both works describing the civilization
that existed hundreds of years before Homer.  The Chinese have a long
history of periodic and devestating self-inflicted Darkness.  It seems
to be a fundemental part of the human character to periodically go
collectively insane and self-destruct.

But the more I studied the model of monastic estates, the more I
became disillusioned with the idea.  By setting yourself apart from
the rest of the culture and civilization you are there to help
preserve you become a perpetual target -- humans are wired to
catagorize each other as either belonging to your group -- one of us
-- and everyone else, who are outsiders or others.  We find it easy to
believe that anyone who is not one of us, is not just different, and
not even an enemy, but evil or not even human and not deserving of
being treated even as well as an animal.  This is how we rationalize
slavery, racism, sexism and  xenophobia.

Universities emerged from the monastic tradition, and continued many
traditions and even titles from european monastaries even today.
Titles like rector, xxxxxxx xxxxxxxx xxxxxxx echo the universities
monastic ancestry.

Universities have often been thought of as /others/ in their
neighboring communities.  The /Town-Gown/ rivalry is as old as
Universities themselves.  The /Latin Quarter/ in Paris, a part of the
city which became the proto-model for the modern university before
they were granted their own land to create campuses had any number of
problems with the rest of the city.  Teachers were granted special
legal status, teachers and students spoke /latin/, which before then
had only been spoken by the clergy, and only heard by commoners during
mass.  No one could read, write or speak latin unless you joined the
church or went to school.  That set them apart.  Because educated
people are /educated/, they sometimes tend to dispense with many
common social customs, and superstitions.  That set them apart.  They
even dressed strangely, in gowns (robes) which definately set them
apart.

It's no surprise that whenever populism or a populist movement is on
the rise, there is a backlash against the educated and especially
against educational institutions.  Time and time again, Univeristies
have been the place where it is thought where uprisings are incubated
and civil unrest instigated.  Purges and even wholesale slaughter of
people in Universities are a far too common occurance throughout
history.  I am writing this in an office of a Univeristy that had all
but two of it's PhDs murdered in my lifetime.  Turkey is the most
recent place to see mass arrests across the country.  The Americans
haven't yet commited broadscale universicide but events like the Kent
State Masacre and before that the darkness of the McCarthy era witch
hunts show that they are not the exception to the rule.

People fear the /other/, so if we are trying to provide very long term
safeguards against our own darker natures the monastic, temple or
university model has almost as many things going for it as it does
against it.

Even if we put aside these misgivings about monastic models, if our
goal is to preserve and safeguard civilization it will always be a
/descriptive/ record.  Knowledge is not just what is in a book, it's
information that has been woven into a person's brain -- knowledge is
always a living thing.  Recorded knowledge, once it has passed out of
living memory is in a sense, lost.  It has to be reinvented in your
head and in your hands from the pages of a book -- weaving that
information into your brain through constant reinforcement and practice.

If you have to choose between rebooting a collapsed civilization from
a neighboring civilization or from a library of books that have been
unearthed after the collapse that recorded what has been lost,
rebooting from the neighbor is a far better option.


