#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Bamboo
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/primer/prim--bamboo.org
  :Created: 2017-02-25T12:23@Prek Leap (11.642600N-104.919210W)
  :ID: 57d8e183-9e3b-47d8-b3d0-70a1992b5f5e
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>

* Introduction


* Guilds

There are two kinds of guilds are often defined as an association of
people working toward a common goal.


At their best Guilds played an important role in maintaining quality
and professional standards, safe guarded knowledge, organized supply
tool chains and were responsible for passing knowledge and skills from
generation to generation.

At their worst through many checkered centuries , guilds exercised
rent seeking, monoplies, political influence, and even murder.


Guilds were, in some cases the prototypes for and the nucleous of
Universities such as Oxford and Paris.

a crop guild is a grouping a plants, trees, animals, insects, and
other components that work together

#+begin_quote
The guild was made up by experienced and confirmed experts in their
field of handicraft. They were called master craftsmen. Before a new
employee could rise to the level of mastery, he had to go through a
schooling period during which he was first called an apprentice. After
this period he could rise to the level of journeyman. Apprentices
would typically not learn more than the most basic techniques until
they were trusted by their peers to keep the guild's or company's
secrets.

Like journey, the distance that could be travelled in a day, the title
'journeyman' derives from the French words for 'day' (jour and
journée) from which came the middle English word journei. Journeymen
were able to work for other masters, unlike apprentices, and generally
paid by the day and were thus day labourers. After being employed by a
master for several years, and after producing a qualifying piece of
work, the apprentice was granted the rank of journeyman and was given
documents (letters or certificates from his master and/or the guild
itself) which certified him as a journeyman and entitled him to travel
to other towns and countries to learn the art from other
masters. These journeys could span large parts of Europe and were an
unofficial way of communicating new methods and techniques, though by
no means all journeymen made such travels — they were most common in
Germany and Italy, and in other countries journeymen from small cities
would often visit the capital.[18]

After this journey and several years of experience, a journeyman could
be received as master craftsman, though in some guilds this step could
be made straight from apprentice. This would typically require the
approval of all masters of a guild, a donation of money and other
goods (often omitted for sons of existing members), and the production
of a so-called "masterpiece,' which would illustrate the abilities of
the aspiring master craftsman; this was often retained by the
guild.[19]

-- [[https://en.wikipedia.org/wiki/Guild][Guild]] | Wikipedia
#+end_quote

A lot of the problem with Guilds is that they had few if any checks
and balances outside their organization.

This needs to be addressed first within their charters, second within
the organization of the guilds themselves, and finally from outside of
the organization.

Some ideas:

  - all guild knowledge must be placed in the public domain under free
    licences that protect it from monologies.
  - guilds should have no representation in civil governance beyond an
    advisory roles.
  - rent seeking is strictly prohibitive, though revenue can be
    generated to cover costs of the organization
  - membership is open to anyone
  - guilds can not own property or companies
  - 

* Bamboo Guild

The idea here is to create a bamboo guild with many different shops
working together to produce things from bamboo in a given bioregion.

  - [[http://bamboocentral.org/index1.htm][EBF-Environmental Bamboo Foundation]] |  Bali, Indonesia
  - [[https://everythingsbamboo.com/bamboo/bamboo-treatment/][Bamboo Treatment]] | Everything's Bamboo
  - [[https://www.guaduabamboo.com/][Guadua Bamboo]]
  - https://www.guaduabamboo.com/bamboo-pdfs/


** Products

  - Building material
    - raw
    - laminate timber
    - plywood
  - Paper
  - Fuel
    - charcoal
    - chips (gasification fuel
  - Food
  - Manufactured
    - furniture
    - buildings
    - bridges

** Species

The five main species for building with bamboo in Indonesia are:

   - Dendrocalamus asper
     - [[https://en.wikipedia.org/wiki/Dendrocalamus_asper][Dendrocalamus asper]]    | Wikipedia
     - [[https://www.guaduabamboo.com/species/?tag=Dendrocalamus+asper][Dendrocalamus asper]]    | Guadua Bamboo
   - Gigantochloa atter
     - [[https://en.wikipedia.org/wiki/Gigantochloa_atter][Gigantochloa atter]]     | Wikipedia
     - [[https://www.guaduabamboo.com/species/?tag=Gigantochloa+atter][Gigantochloa atter]]     | Guadua Bamboo
   - Dendrocalamus strictus
     - [[https://en.wikipedia.org/wiki/Dendrocalamus_strictus][Dendrocalamus strictus]] | Wikipedia
     - [[https://www.guaduabamboo.com/species/?tag=Dendrocalamus+strictus][Dendrocalamus strictus]] | Guadua Bamboo
   - Gigantochloa apus
     - [[https://en.wikipedia.org/wiki/Gigantochloa][Gigantochloa]]           | Wikipedia
     - [[https://www.guaduabamboo.com/species/gigantochloa-apus][Gigantochloa apus]]      | Guadua Bamboo
   - Guadua angustifolia
     - [[https://en.wikipedia.org/wiki/Guadua_angustifolia][Guadua angustifolia]]    | Wikipedia
*** Nan Bamboos Thailand

  - Dendrocalamus giganteus
    - [[https://en.wikipedia.org/wiki/Dendrocalamus_giganteus][Dendrocalamus giganteus]]  | Wikipedia
    - [[https://www.guaduabamboo.com/species/dendrocalamus-giganteus][Dendrocalamus giganteus]]  | Guadua Bamboo
    - [[https://www.youtube.com/watch?v=uBApCRE95C4][Giant Bamboo Biggest in Thailand]] | YouTube

** Treatment

   - [[https://www.youtube.com/watch?v=GRc3TxL1sn8][Guadua Bamboo Harvest and Treatment Process]] | YouTube

 - Vertical Infusion Method
 - Bouchrie Method
** Equipment

 - [[http://www.garnetindia.com/][Garnet India]] | Bamboo Processing Equipment
 - [[https://www.youtube.com/watch?v=fpn0QZvvazs][Bamboo Universal Machine]] | YouTube
 - [[http://www.garnetindia.com/262_Uni_wdwrkg.html][262 Universal Woodworking Bamboo Application Machine]] | Garnet India
   garnetindia@gmail.com 
   info@garnetindia.com

** Poles
** Chipping (fuel)
** Plywood

  - [[http://intectural.com/material/plyboo/][Plyboo – Bamboo Plywood Building Material]] | Intectural
  - 

Soybased adhesives
