#   -*- mode: org; fill-column: 60 -*-
#+STARTUP: showall

* Chenla Primer | README
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/primer/README.org
  :Created:   2017-06-22T11:32@Prek Leap (11.642600N-104.919210W)
  :ID:        52006095-bb9d-4c8e-9c4e-0371ea047e5c
  :VER:       551378037.400867942
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:NDR7-8802
  :Class:     primer
  :Type:      readme
  :Status:    stub
  :Licence:   MIT/CC BY-SA 4.0
  :END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]]
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-readme-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-stub-CC79A7.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

In the space of a single lifetime our species has gone from several
semi-autonomous civilizations spread around the planet to a single
global interconnected civilization.  Not only is this a single point
of failure, the civilization we have built is so mind-boggling complex
that no one has any idea what information is critical to the
maintenance and survival of our civilization.  We have allowed
critical parts to collect in technological tidal pools.  If two or
three or such tidal pools get destroyed at the same time, it could
easily create a chain reaction that could result in regional and even
global collapse.

The Primer is a catch-all for all information required to build and
maintain a distributed scopic civilization.  So it is not a single
work that would be published as a single or even multiple volume work,
but a library of descriptive and proscriptive narratives,
specifications, code, semantic rulesets, designs, images, audio,
video, vector 2d and 3d models and tabular data.  The source code and
source media for the Primer can be processed and rendered in a wide
variety of formats that will represent snapshots of subsets of the
Primer for use in different contexts.

The Primer is meant to be a living document, not just used as a manual
for reconstructing civilization, but a daily reference that reflects
the state of the art, that attempts to capture a living civilization
at any given moment.  

That would be ambitious in itself, but aim is to go much further so
that the Primer becomes the generative source code for civilization
itself.  We say generative, because designs emerge from patterns, and
combined with experience, and the context that defines the
requirements that a design that can help solve problems.  So the
Primer is not a cookbook or blueprint that is fed into a machine or
system to create identical copies.

No civilization is static.  Civilizations must constantly dynamically
iterate to adapt to change, even if that change is not perceived as
growth, simply keeping a civilization from falling into decline and
collapse is a non-trivial achievement.

Even if this Primer is not successful, something like it will need to
evolve as a mechanism to maintain our present civilization and to
survive catastrophes both natural and man-made that could disrupt the
delicate balance that exists now and send us spiraling into an abyss
which way may not be able to recover from.

In this sense, the Primer should be considered to be of vital
strategic importance to everyone from individuals to nation-states.
