#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Saltmine Platform TL;DR
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/tldr/saltmine-platform-tldr/saltmine.org
:Created:   2017-06-11T19:37@Prek Leap (11.642600N-104.919210W)
:ID:        2f2c69a5-20d4-42f6-b250-0e4b7a7ce8dd
:VER:       558410904.792047663
:GEO:       48P-491193-1287029-15
:BXID:      proj:FOB3-1423
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

* TL;DR

Saltmine is a platform for providing the information infrastructure
for a technological distributed civilization.  Not ambitious in the
least...

We can think of the universe as information-centric in its very bones.
Every quantum event is binary which determines the process of
becoming.  Time and entropy requires that nothing is static and
nothing is forever.  Everything is in the process of becoming
something else.  The very idea that anything is permanent or static is
an illusion steming from our human scale.  What is happening on scales
smaller and larger than ourselves is invisible, or at least not
obvious to us.  Atoms are not solid objects like a billard's ball that
are numbered and weighted by the periodic table, they are constantly
changing probability clouds of electrons and neutrons popping in and
out of existence from one moment to the next.  And every change
generates information, or perhaps it is the information that generates
change.  Matter, energy, space and time may well be the compiled form
that information takes like the polygons rendered by a 3D model.

Our brains are electrochemical computers. Most brains have firmware
that is hardwired and has limited ability to adapt to situations that
have not been preprogrammed.  Reptiles fall firmly into this category.
But our neocortex is far more flexible, than the limbic and reptilian
brains that it wraps around.  The neocortex can be thought of as
programable, and somewhat capable of transcending the programing that
came with it at birth.  I say somewhat, because we take much more
credit for ouselves and our abilities than we should.  The human brain
might be a marvel, but it is very much a marvel with some hard
limitations.  We can only keep a small number of ideas in active
memory at any one time.  We still listen to our more primitive
subsystems like the limbic system that can lead to some pretty bone
headed behaviors.  And the very thing that makes the neocortex so
powerful -- it's ability to recognize patterns -- can work against us
when there are false positives.  The real marvel is not that we can
program ourselves, but that we have found ways of harnessing the
outside world to extend our mind and muscle in ways that transcend our
physical and cogntive shortcomings.

Saltmine is an attempt to consolidate and harness the information and
processes generated by these cognitive and physical externalizations
no matter what technological form they take so that they become a more
natural extension of our selves as individuals and collectively as
groups and it is hoped, as a species.

At first, statements like this might sound at best like hubris, and at
worst, as delusions of grandeur.  But if so, this is a description of
all techological advances from the first crude hand-tools, to speech
and writing systems, the printing press, Charles Babbage's Difference
Engine, Vannevar Bush's Memex Machine, Dewey's Decimal Classification
system, Ted Nelson's hypertext and Tim Berners Lee's more pragmatic
expression of it that became the World Wide Web.  Hand tools became
machines, which were then connected to water, wind, and beasts as
power sources.  Eventually these sources were displaced by steam,
internal combustion and then electricity.  Computation moved from
inside our heads onto paper and the noisy clack of the abacus and
eventually to electronic logic gates which have now shrunk to single
digital nanometer scales.

Saltmine is built on top of all of that and more -- an attempt to, as
the poet Charles Olson liked to say, move the stick a little further
up the beach.

What characterizes Saltmine is that it is atempting to bring the wide
variety of information that is now available from the past 30 years of
digitizing all forms of information, together and make them both
legible and interoperable with each other.

The now billions and soon trillions of network connected devices,
which might be as simple as the water valve on a water trough on a
cattle ranch in the Australian Outback that keeps track of how full it
is, to a crewless container ship somewhere in the vast Pacific ocean
going from Tokyo to Mexico, to a supercomputer managing millions of
trades per second in Hong Kong for the Hang Seng index.  This is all
on top of the countless cat, wedding, and baby pictures that are
shared once and never retrieved again into the bowels of a Facebook
datacenter, the broken stream of consciousness on Twitter from Donald
Trump in the early hours of the morning, or the the surge of 60
million hopeful people in Thailand checking the week's lottery numbers
even as the plastic balls are being pulled out and unscrewed to reveal
the numbers inside.

Today all of this information is a patchwork plumber's nightmare of
different services, APIs and walled gardens.  Very little of this
information can be understood by any other system, and end users have
all of their information siloed on different devices, apps, storage
media, and cloud services.

The power and value of all of this information if it were was all
machine legible and interoperable is incalculable.  But it can't be
done by any one group or company.  If it's monopolized it won't work.
It can't be centralized, or even decentralized for it to work.  It
must be completely distributed and scale from the smallest device to
the largest Googleplex.

For a brief, shining moment in history, the Web almost did this.  But
was crushed by Microsoft who quickly tried to make the Web their own
proprietary network by making it work only on their software.  That
power grab failed, but companies emerged who are now as big or bigger
than Microsoft who have very nearly pulled it off; namely Facebook and
Google.  Google's AMP and Facebook's Instant pages are a major
abandonment of the Open Web.

As bleak as things look now, it is still very early days for the Web
which has only been around for about 20 years.  The Web is now largely
being shaped by the mobile phone revolution that is only about 8 years
old.  The limitations of tiny displays that fit in a pocket has
resulted in the worst aspects of centralization, consolidation and
monopolization.  And the vast majority of people don't understand what
they are giving up to be able to load a cat picture on their phone a
few milliseconds faster than before.

But as we said, these are still very early days and how the Web will
be 10 years from now will certainly bare little resemblance to today's
web.  The mobile revolution is set to be devoured whole by what will
come over the next decade.

Today's mobile phone is a bit like the PC of the 1990's which was
powerful, but isolated.  We now build phones as little stand alone PCs
we keep in our pockets.  Display technology will soon become a
building material.  Everything will become a display.  Our table tops,
walls, windows, floors, roofs.  The Internet and the Web will no
longer be confined to what fits in your jeans.  The Web will become
quite literally the furniture in the room.  And today's mobile
app-centric eco-system which is designed for single user, personal
devices will become the equivilent of all of those dozens of crappy
windows toy applications that we all installed before the Internet and
Web connected everything together.  Displays will have to become
collaborative so that anyone and everyone in the room can use them.
Apps don't scale.  And as the resolution and size of displays
increases, centralized infrastructure will begin to hit physical
limits of bandwidth.  The speed of light is not something you can get
around.  So processing will have to move closer to where it is used,
which is at the edges of networks.  This favors distributed systems.
The latency and speeds that AMP give mobile users today, can not scale
to floor-to-ceiling wall sized displays.

Then we have companies like Amazon and Alibaba who provide:

  - product discovery
  - warehousing
  - delivery
  - payment

All of these functions are essentially different types of middlemen.  

What happens when these services become part of a distributed network
and not a service that any one company provides.  Self driving cars
and trucks don't even need to be owned by anyone.  They can be owned
by themselves -- and even save money to repair and even replace
themselves over time.  That might sound fantastical today, but once a
car can drive itself, and accept and process payments itself, and
establish themselves as some sort of semi-autonomous legal corporate
entity why would you need companies like Uber who have nothing left to
offer except a brand name?

What happens when supply chains, and production chains can self
organize and reconfigure themselves for every order, so that, supply,
production, transactions and transportation become something like a
bit-torrent for manufacturing?  Where does Alibaba and Amazon fit into
that world?  They will be tomorrow's Long Shoreman, that were replaced
by palletization and containerized transportation systems.

How will all of this become possible?  As Kevin Kelly has pointed out,
in the nineteenth century countless fortunes were made by electrifying
anything that was mechanical.  You only had to point at something
people used or did every day and made it electrical.  This same
process is about to repeat itself, but with artificial intelligence.
AI is not about Terminator's or humanoid robots.  It's about
automating anything that is electrical.  Point at anything you do or
use today using electricty and add AI and you will make a fortune.

The difference is that all of these things will be networked together
and able to talk to each other, which will amplify the power and
impact of each of these innovations.

The sum will not only be greater than its parts, it will result in a
world where everything externalizes and extends everything, including
-- in fact especially -- us.  We will not be sidelined or cut out,
rather we will become increasingly woven into this new smart fabric so
it will become more and more difficult to know where we end and the
network starts.


* Saltmine Content Types

 - work  :: literate source 
 - data  :: tabular data
 - graph ::
 - build ::
 - blob  :: binary large object
 - burr  :: record
 - rule  ::  

* Package Formats

  | Rendered/Published end user content (html,epub,pdf etc) |
  | Source File Packages                                    |
  | Application Packages & Running Code                     |
  | Container                                               |
  | Operating System                                        |


  | Type      | ext              |                                      |
  |-----------+------------------+--------------------------------------|
  | Epub      | .epub3/.epubd    | Portable publishing package format   |
  | Hoard     | .hoard           | Content source package format        |
  | Package   | .pkg             | Linux application package format     |
  | Container | .dockerfile/.rkt | Containerized process package format |

* Hashes & Checksums

break into sections:

  - content hashes
  - ipfs hashes
  - ipns hashes


#+begin_example
cf88430390b98416d1fb415baa494dce *08. Allow Your Mind To Wander.mp3
#+end_example

* Open Annotation Format

Epub requires to be in JSON format

  - [[http://www.idpf.org/epub/oa/][Open Annotation in EPUB]] | IDPF

I want to be able to use wiki source files as well as json
-- but this to work, we MUST be able to roundtrip between
the two formats -- this means that whitespace is ignored for
glosses and commentary.  Scholia are wiki source files in
their own right -- but point to block level or inline
content in other files.  Software will generate links.
