#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Hoard TL;DR
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/tldr/hoard-tldr/hoard.org
:Created:   2017-06-07T15:37@Prek Leap (11.642600N-104.919210W)
:ID:        45e12c34-c376-4018-b17d-e4b2f3827d69
:VER:       558408470.352407736
:GEO:       48P-491193-1287029-15
:BXID:      proj:YHB5-6557
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

#+begin_quote
*wordhord*, /n/: a word-hoard, a store of words

before 12thC
#+end_quote

* TL;DR

A hoard is a collection of source content that is either
bundled with a running containerized process, or as a tar
file (sans the container) that can be used for transport and
archiving.

As a running process, a hoard does conversion into rendered
human consumable formats, and indexes that become part of
graph databases.

Running hoards (no pun intended) are also responsible for
maintaining copies of themselves through ipfs -- ipfs does
not ensure that copies are maintained, any more than
bit-torrent does.  So a running hoard watches that there are
always x number of copies being archived and x number
running at all times.

We will need a consensus mechanism for shutting down a
running hoard -- perhaps each maintains an active number that
represents how often it is being accessed -- if 10 running
copies are supposed to be maintained, and there are more
than 10 copies running -- each copy will poll the others to
see who has the lowest activity and delete themselves until
they are back to 10.  Higher activity raises the number
being maintained.

* Hoard Package Manifest

  - source files :: org or md
  - annotations :: annotate.org/annotate.md -> export to annotations.json
  - datafiles :: tabular data
  - css/*.css :: cascading style sheet files
  - crs/*.crs :: cascading ruleset of ducktests
  - colophon :: literate toolchain -- build file
  - idx/graph :: property graph index of contents
  - media/*.png|mp4|svg :: images, videos & vectors
  - meta/mimetype :: declare mimetype for hoard package
  - meta/keys :: public keys, if any
  - meta/hash :: hashes and checksums (sections for file/ipfs etc)

* Media Hoard Manifest

Media hoards are packages that contain original lossless
formats of media.

You can include application specific formats -- but if you
do you *MUST* include a version in an open lossless
archival format.

  - export   :: list of formats and resolutions export to
  - build    :: build file for converting files
  - metadata :: associated metadata descriptions

This is sort of like Wikipedia's MediaWiki where each image
and media file has their own page dedicated to describing it
and provide conversions to different formats and resolutions.

* Hoard Components

Each hoard breaks down into a number of different parts that
provide different functions:

 - Source  :: human readable source file formats (xml and
              html are not)
 - Build   :: processing and build files -- takes source and
              applies rules to generate rendered formats and
              graph index.
 - Format  :: style sheets for rendered output
 - Index   :: graph index for source files and annotations
              (key-value & keyword) that can be woven into
              horcrux db
 - Version :: version control -- which at the moment is git
 - Media      :: rendered end-user media files -- source
                 files are maintained in their own
                 media-hoard packages.
 - Fonts      :: ttf font files
 - Annotation :: local or shared commentary, glosses and scholia


* References

 - [[https://en.wikipedia.org/wiki/Hoard][Hoard]] | Wikipedia

#+begin_quote
image credits

Gustave Doré - Dante Alighieri - Inferno - Plate 22 (Canto
VII - Hoarders and Wasters)

-- [[https://en.wikipedia.org/wiki/Gustave_Dor%C3%A9][Gustave Doré]] | Wikipedia

Punishment of the Avaricious and the Prodigal

Creator: Doré, Gustave
Date: 1890
Medium: woodcut
Source: Dante Alighieri's Inferno from the Original by Dante
Alighieri and Illustrated with the Designs of Gustave Doré
(New York: Cassell Publishing Company, 1890).
#+end_quote
