#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Consolidation-Disruption Cycle TL;DR
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/tldr/disruption-cycle-tldr/disruption-cycle.org
:Created:   2017-06-07T18:09@Prek Leap (11.642600N-104.919210W)
:ID:        15c5a150-7369-4fc8-a586-5159fdd69e30
:VER:       558408037.009456415
:GEO:       48P-491193-1287029-15
:BXID:      proj:VHC1-0481
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

* Discussion


* TL;DR

 - Centralized
 - Decentralized
 - Distributed

 - Timeline

Technological revolutions break up centralized systems into
a distributed system where the power is at the edge of the
networks.  Over time, consolidation occurs into a
decentralized network made up of a large number of medium
sized organizations.  Finally these mid-sized organizations
consolidate into a handful or even a single organization
that monopolizes the network.

As networks consolidate into decentralized and then
centralized systems, innovation slows down, creating a
power-wealth-value imbalance that is not sustainable.

In 2017 the Internet & The Web, which started as a
distributed network, consolidated to the point where the
number of players can almost be counted on one hand.

We are at the beginning of no less than five revolutions;
artificial intelligence, robotics, nanotech, trustless
distributed networks (based on cryptography, hashes, and
distributed ledgers) and a biological revolution based on
gene splicing technologies such as CRSPR.

Any one of these technologies alone would constitute change
at the same scale as Gutenberg's Press, The Industrial
Revolution, The Computer and Internet Revolutions.  Taken
together each of these revolutions will amplify, and
reinforce each other.  The next 5-20 years will
fundamentally reshape business, finance, manufacturing,
transportation, energy, agriculture, medicine, education,
government and the world order.  Simply put, we are seeing
changes that will transform human civilization to the point
that it can be called a Singularity; a future that we can
not predict or even imagine today.



* Sidebar

 - [[bib:wu:2010master][The Master Switch]] | Tim Wu (2010)
 - [[https://en.wikipedia.org/wiki/Tim_Wu#The_Master_Switch][Tim Wu - Wikipedia]]

 - The Third Wave | Alvin Toffler
 - Power Shift    | Alvin Toffler 
